Initialize keyvaluestore
defoeam/kvs pull request #5
Opened 2024-08-02 19:17 UTC by tkoivi

Initialize kvs based on blog post

Tested with curl commands demonstrated in post.

2024-08-02 19:26 UTC, louislef299 commented
Just need to rebase with main to fix that merge conflict. You can do that by running:

```bash
git checkout main
git pull
git checkout feature/init-kvs
git rebase main
```

2024-08-02 19:33 UTC, defoeam requested changes
One quick change: can you change the "keyvaluestore" package name to "kv"?
It will be "github.com/defoeam/kvs/kv" in main.go.

2024-08-02 19:48 UTC, louislef299 commented
Could we also write the [tests in Go](https://go.dev/wiki/TableDrivenTests)?

2024-08-02 19:54 UTC, defoeam commented
> Could we also write the [tests in Go](https://go.dev/wiki/TableDrivenTests)?

Yeah for sure! I haven't tried table-driven tests yet but this looks promising

2024-08-06 18:39 UTC, defoeam submitted a review, later dismissed

2024-08-06 19:20 UTC, louislef299 commented on main.go
> +	err := server.ListenAndServe()
```suggestion
	log.Fatal(server.ListenAndServe())
```

nit: You can just wrap the listen and serve function in a log.Fatal error. Feel free to close this if you would like to just get this merged.

2024-08-06 20:04 UTC, defoeam commented on main.go
> +	err := server.ListenAndServe()
Fixed

2024-08-06 20:05 UTC, defoeam submitted a review, later dismissed

2024-08-06 20:49 UTC, louislef299 approved these changes

2024-08-06 20:49 UTC, merged